name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.check_commit.outputs.should_publish }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check commit message
        id: check_commit
        run: |
          commit_msg=$(git log -1 --pretty=%B)
          if [[ $commit_msg =~ ^chore\(hyprshell.*\):\ release ]]; then
            echo "should_publish=true" >> $GITHUB_OUTPUT
          else
            echo "Error: Commit message must start with 'chore(hyprshell): release'"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.should_publish == 'true'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install gtk4-layer-shell
        working-directory: /tmp
        run: |
          sudo apt-get update
          sudo apt -y install git libglib2.0-dev libgraphene-1.0-dev meson ninja-build libwayland-dev libgtk-4-dev gobject-introspection libadwaita-1-dev libgirepository1.0-dev python3 valac
          git clone https://github.com/wmww/gtk4-layer-shell
          cd /tmp/gtk4-layer-shell
          meson setup build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
      - name: Install cargo-workspaces
        run: |
          mkdir -p $HOME/.cargo/bin
          cargo install cargo-workspaces
      - name: Publish to crates.io
        run: |
          set -euxo pipefail
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch --tags origin hyprshell-release
          git checkout ${{ github.ref }} -b hyprshell-release
          git log -1 --pretty=%B
          git push origin HEAD:hyprshell-release --force
          git switch hyprshell-release
          
          current_sha=$(git rev-parse HEAD)
          jq --arg sha "$current_sha" '.["last-release-sha"]=$sha' release-please-config.json > tmp.json && mv tmp.json release-please-config.json
          git add release-please-config.json
          git commit -m "chore(release): update last-release-sha"
          git push origin hyprshell-release
          
          git tag --delete ${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}
          
          version=$(echo ${{ github.ref_name }} | sed 's/v//')
          cargo ws publish custom $version -m "chore(release): bump rust versions to $version" --no-individual-tags --allow-branch hyprshell-release --exact --yes --force "hyprshell*" --token ${{ secrets.CRATES_TOKEN }}
          
          # push current branch to hyprshell branch (for development)
          git fetch origin hyprshell
          git push origin HEAD:hyprshell
          
          gh release edit ${{ github.ref_name }} --latest --draft=false --title "hyprshell ${{ github.ref_name }}"

          cargo build --release --target x86_64-unknown-linux-gnu
          gh release upload ${{ github.ref_name }} "target/x86_64-unknown-linux-gnu/release/hyprshell#hyprshell-x86_64-unknown-linux-gnu"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@2ac5a4c1d7035885d46b10e3193393be8460b6f1 # v4.1.1
        with:
          pkgname: hyprshell
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update hyprshell AUR package
          updpkgsums: true
          ssh_keyscan_types: rsa,ecdsa,ed25519
      - uses: cachix/install-nix-action@456688f15bc354bef6d396e4a35f4f89d40bf2b7 # v31.8.2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "download-buffer-size = 5368709120"
      - uses: cachix/cachix-action@v16
        with:
          name: hyprshell
          extraPullNames: hyprshell-dev
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run Nix Flake Check build
        run: nix build '.#packages.x86_64-linux.hyprshell' -L

