name: test

on:
  push:
    branches-ignore:
      - 'release-please-**'
      - 'hyprshell-release'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-nix:
    name: Run Nix Flake Check
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "download-buffer-size = 5368709120"
      - uses: cachix/cachix-action@v16
        with:
          name: hyprshell-dev
          pushFilter: "hyprshell-(nextest|clippy|fmt|check-all-feature-combinations|check-nix-configs).*"
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN_DEV }}
      - name: Run Nix Flake Build deps
        run: nix build '.#checks.x86_64-linux.hyprshell-build-deps' -L
      - name: Run Nix Flake Check build
        run: nix build '.#checks.x86_64-linux.hyprshell-config-check' -L
      - name: Run Nix Flake Check clippy
        run: nix build '.#checks.x86_64-linux.hyprshell-clippy' -L
      - name: Run Nix Flake Check fmt
        run: nix build '.#checks.x86_64-linux.hyprshell-fmt' -L
      - name: Run Nix Flake Check test
        run: nix build '.#checks.x86_64-linux.hyprshell-test' -L
      - name: Run Nix Flake Check check-nix-configs
        run: nix build '.#checks.x86_64-linux.hyprshell-check-nix-configs' -L
      - name: Run Nix Flake Check check-all-feature-combinations
        run: nix build '.#checks.x86_64-linux.hyprshell-check-all-feature-combinations' -L

  check:
    name: Run build tests
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/hyprshell'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: hyprshell
          cache-on-failure: true
      - name: Build binary for x86_64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell.sh
          ./scripts/ci/build-x86.sh
      - name: Build binary for aarch64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell-aarch64.sh
          ./scripts/ci/build-aarch64.sh

