name: test

on:
  push:
    branches-ignore:
      - 'release-please-**'
      - 'hyprshell-release'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run Nix Flake Check
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "download-buffer-size = 5368709120"
      - uses: cachix/cachix-action@v16
        with:
          name: hyprshell-dev
          pushFilter: "hyprshell-(nextest|clippy|fmt|check-all-feature-combinations|check-nix-configs).*"
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN_DEV }}
      - name: Run Nix Flake Build deps
        run: nix build '.#checks.x86_64-linux.hyprshell-build-deps' -L
      - name: Run Nix Flake Check build
        run: nix build '.#checks.x86_64-linux.hyprshell-config-check' -L
      - name: Run Nix Flake Check clippy
        run: nix build '.#checks.x86_64-linux.hyprshell-clippy' -L
      - name: Run Nix Flake Check fmt
        run: nix build '.#checks.x86_64-linux.hyprshell-fmt' -L
      - name: Run Nix Flake Check test
        run: nix build '.#checks.x86_64-linux.hyprshell-test' -L
      - name: Run Nix Flake Check check-nix-configs
        run: nix build '.#checks.x86_64-linux.hyprshell-check-nix-configs' -L
      - name: Run Nix Flake Check check-all-feature-combinations
        run: nix build '.#checks.x86_64-linux.hyprshell-check-all-feature-combinations' -L
