name: update flake.lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '30 2 1,15 * *' # At 02:30 on every 14th day-of-month.

jobs:
  nix-flake-update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update flake
        run: |
          git fetch
          git switch hyprshell
          nix flake update
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          git commit -m "fix(nix-flake): update flake.lock"
          git push origin hyprshell
